name: webshop
stages:
- name: clone
  steps:
  - sourceCodeConfig:
      branch: master
      branchCondition: only
      url: https://github.com/VladButacu/mywebshop.git
- name: publish
  steps:
  - publishImageConfig:
      buildContext: .
      dockerfilePath: ./Dockerfile
      tag: vbutacu/webshop:latest
triggerWebhookPush: true

